# Generated by Django 5.1 on 2024-08-13 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('apk_file_path', models.FileField(upload_to='apk/app/')),
                ('first_screen_screenshot_path', models.ImageField(blank=True, null=True, upload_to='apk/images/first_screen_screenshot_path/')),
                ('second_screen_screenshot_path', models.ImageField(blank=True, null=True, upload_to='apk/images/second_screen_screenshot_path')),
                ('video_recording_path', models.FileField(blank=True, null=True, upload_to='apk/video/')),
                ('ui_hierarchy', models.TextField(blank=True, null=True)),
                ('screen_changed', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
