# Generated by Django 5.1 on 2024-08-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmanagement',
            name='first_screen_screenshot_path',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='apk/images/first_screen_screenshot_path/'),
        ),
        migrations.AlterField(
            model_name='appmanagement',
            name='second_screen_screenshot_path',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='apk/images/second_screen_screenshot_path'),
        ),
    ]
